# Generated by Django 3.1 on 2021-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
                ('category_slug', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, max_length=200)),
                ('category_image', models.ImageField(blank=True, upload_to='images/categories')),
            ],
        ),
    ]
